### PR TITLE
Ogg flac

### PR DESCRIPTION
**Pull request by philippe44**
This PR adds OggFlac as a recognized type in Audio::Scan. This also requires types.conf to be modified in LMS to be fully functional). 

I also had to change some of the core Ogg binary search algorithm to find frames. I really do think there was an issue there. The problem is that the Ogg standard says that when a page does not terminate any packet, then the granule pos should be -1 (not sure if this is a "might" or "shall"...). The current binary search does not take tha tinto account and blindly uses the granulepos to decide where it is in the search. That does not work, but probably was not very obvious as most vorbis and opus files have only a few pages that don't end packets. Now, when you use flac as the codec, it tends to happen much more. 

I've added quick tests and it also passed the existing tests as required. I've tried on my aarch64 and it works. (NO)

I did not realize I had commit rights on the repo and inadvertently pushed my version. I've hard reset that, so it should be fine as @ralph-irving is the official maintainer, AFAIK.

### CODE REVIEW

**Comment by 986ster** [comment]
Are you expecting OggFlac files to have a discrete extension (e.g. .ogf), or should they be a regular .ogg file? If you can let me know what needs to be in convert.conf (or custom-convert.conf if it makes sense to use that instead) then I can test this file type now that I can seemingly create it.

I have the compiler installed on my test server, and I've already compiled 1.09 anyway, so I'm familiar with doing that. I just don't happen to have the compiler and dev libraries installed on my production Intel server as I keep that build really clean, but that's not really important for this purpose.

**Comment by philippe44** [comment]
They have to have a different extension, otherwise LMS won't be able to differentiate them. The best file to modify is types.conf
```
ogg     ogg,oga         audio/x-ogg,application/ogg,audio/ogg,application/x-ogg       audio
ogf     ogf             audio/ogg;codecs=flac           audio
ops     opus            audio/opus,audio/ogg;codecs=opus audio
```

**Comment by 986ster** [comment]
Got this version installed and I was able to seek in Ogg Vorbis and Opus files just fine, jumping forwards and backwards. Ogg Flac files in 44.1kHz/16-bit and 96kHz/24-bit played, but I couldn't seek at all. The web UI didn't do anything when I clicked on the track progress bar.

**Comment by philippe44** [comment]
That's strange. I've tried again and I can seek as expected. Do you have the file's information when you click on it? Sorry to ask, but are you you have copied Scan.pm and Scan.so at the right place?

**Comment by 986ster** [comment]
I have scan.so in /usr/share/squeezeboxserver/CPAN/arch/5.36/aarch64-linux-thread-multi/auto/Audio/Scan and Scan.pm in /usr/share/squeezeboxserver/CPAN/arch/5.36/Audio.

LMS is reporting Audio::Scan 1.10 on the Information page, and if I click on one of the files, I get information like this, which suggests that it's properly recognising and scanning the files:

File Format: Ogg FLAC
Duration: 4:15
Sample Rate: 44.1 kHz
Sample Size: 16Bits
File Length: 21,500,084 

I also checked my source, and I have the ogf sources, so it's not like I pulled the first commit in your PR where you just upped the version.

Any thoughts on where to look?

**Comment by philippe44** [comment]
Oh crap, I totally forgot to update the OggFlac Perl part. It worked on my tests because when seeking, I had a rule ogf -> pcm that has a skip option and so LMS was using that to transcode _and_ skip. I'll do update of Format::OggFlac.pm

**Comment by 986ster** [comment]
Okay, good. Glad there's an explanation for why we've been seeing different behaviour. I'll test it again with the Perl part once you've got that ready.

**Comment by ralph-irving** [comment]
Sorry, I've been away and haven't had time to help with testing. Let me know when you're happy with these changes and I will create a 1.10 release and build audio::scan for windows 32 and 64bit.

**Comment by philippe44** [comment]
No worries, I got your previous message. I'm finishing the Perl code that goes together, I forgot a few things (some players want a header and can't deal with just ogg alignment). I'll post here as soon as it is ready

**Comment by philippe44** [comment]
I've added the support now https://github.com/Logitech/slimserver/pull/987

**Comment by philippe44** [comment]
There is still on issue on my aarch64 platform that I don't see on Win64, so this is not ready yet

**Comment by 986ster** [comment]
I've got all the changes applied and, from what I can see, seeking in OggFLAC files both forwards and backwards seems to be working just fine.  I've tested with 44.1kHz/16-bit and 96kHz/24-bit files so far, and when you choose a time on the progress bar in the web UI or in iPeng, the track position moves to just about half a second prior to that point, and seems to be consistently getting to the right place.

Is there anything in particular you want tested on this, so I can make it more targeted?

Interestingly, having just noticed your comment preceding this one, I'm testing on aarch64 too. What issue are you seeing with this platform?

**Comment by philippe44** [comment]
It's surprising that it works on your aarch64. I realized I left some critical issues with file management that made native seeking impossible (native = seeking using ogf, not seeking with ogf -> pcm conversion).

Anyway, I've now updated that, both here and in the LMS PR, so that would be amazing if you could test that in details, including also verify the lack of impact for Vorbis and Opus files. Playing, Pausing, Seeking, moving next and previous ...

**Comment by 986ster** [comment]
I saw the other changes to FLAC, Movie, and OggFLAC.pm that you put out there.  I'll pick them up later and test again with Ogg-FLAC, Vorbis, and Opus files.  I had tested them this morning and they were still working okay, but I will retest with the updated code, and also with pausing, resuming, and skipping between files.

**Comment by philippe44** [comment]
There is still one case I found on my own setup, so I'll let you know when at least I don't find any issues on my side

**Comment by 986ster** [comment]
I've found one issue so far with these changes, in an OggFLAC file where I did a forward seek to 2:15 in a 4:15 long track and it immediately skipped to playing the next track. I don't know if this is the issue you're working on, or a new one.

**Comment by philippe44** [comment]
Well, I think (I hope) that this time this is correct...

**Comment by 986ster** [comment]
I've tested seeking and skipping with FLAC, Ogg Vorbis, Ogg FLAC, and Opus files today, with the latest Audio::Scan code from last night. I can't get it to fail at all, and it's hitting the right seek points each time. Ogg Vorbis seemed to be a little slow to perform the seek at first, but that may be a format-related thing.  It's not a format I use generally, other than for streaming, so I have very little experience with it as a local format. I also made a point of including some high-res Ogg FLAC as well, so I've tested with more than one bitrate.

**Comment by philippe44** [comment]
Thanks so much! As said, writing code is quite often the easy part, testing & validation is really the difficult one. It means the world for people like me, doing things open & free, to have you doing these tests.

**Comment by 986ster** [comment]
It's the least I can do to help give something back for everything that you and the other developers have put into this product. I've been using it for over 15 years now, and the support easily on a par to what it was when it was an official product with paid staff.

**Comment by ralph-irving** [comment]
Can you add the test.ogf, picture.ogf, large-comment.ogf and headers.ogf files to the PR?
I'm trying to create a test build for win32 and had to change a few lines as Visual Studio 2008 doesn't support the adding to a void pointer GCC extension. I'd like to confirm that my changes at least still pass the tests before posting them.
Thanks.

**Comment by philippe44** [comment]
I think these files are already here, no? At least I can see them in the t/ogf/ directory. Regarding the changes for VS2008, indeed only gcc allows arithmetic on void* but you don't use the strawberry built-in gcc to build the dll? That's what I did for my Windows tests.

https://github.com/LMS-Community/Audio-Scan/pull/5/files#diff-a0948f4b84a19514bfff854fe07482f02a4298d6c8f31471de0bd8b96dd9142f

**Comment by ralph-irving** [comment]
That's weird, the test files aren't included in the 5.diff file. I haven't come across that problem before, so I just assumed they weren't included.  Sorry, I should have confirmed first.

As to VS2008, the win32 release uses activestate perl 5.14 which requires modules be built with the old compiler.  Yes, I do use the gcc bundled with Strawberry Perl for win64.

Unfortunately, I won't have time until tomorrow to revisit the testing.

**Comment by ralph-irving** [comment]
I hope it's not me again but I don't see headers.ogf which is also referenced beginning at line 91 of ogf.t?

https://github.com/LMS-Community/Audio-Scan/pull/5/files#diff-a0948f4b84a19514bfff854fe07482f02a4298d6c8f31471de0bd8b96dd9142f

**Comment by philippe44** [comment]
It's generated by the first part of the test. The objective is to verify that the extracted and regenerated header is correct.

**Comment by ralph-irving** [comment]
As a test point, I built audio:scan with just the changes in this PR, none of my own, using 64bit strawberry perl and the ogf tests fail.
```
t/ogf.t ............ Error: Unable to read at least 10 bytes from file.

#   Failed test 'Audio offset ok'
t/ogf.t ............ 1/45 #   at t/ogf.t line 22.
#          got: undef
#     expected: '8498'

#   Failed test 'Bitrate ok'
#   at t/ogf.t line 23.
#          got: undef
#     expected: '215793'

#   Failed test 'Bits per sample ok'
#   at t/ogf.t line 24.
#          got: undef
#     expected: '16'

#   Failed test 'Channels ok'
#   at t/ogf.t line 25.
#          got: undef
#     expected: '2'

#   Failed test 'File size ok'
#   at t/ogf.t line 26.
#          got: '0'
#     expected: '52358'

#   Failed test 'Max blocksize ok'
#   at t/ogf.t line 27.
#          got: undef
#     expected: '4096'

#   Failed test 'Max framesize ok'
#   at t/ogf.t line 28.
#          got: undef
#     expected: '2501'

#   Failed test 'MD5 ok'
#   at t/ogf.t line 29.
#          got: undef
#     expected: 'b8b878af74e8401474ef7754aaedac47'

#   Failed test 'Min blocksize ok'
#   at t/ogf.t line 30.
#          got: undef
#     expected: '4096'

#   Failed test 'Min framesize ok'
#   at t/ogf.t line 31.
#          got: undef
#     expected: '1414'

#   Failed test 'Samplerate ok'
#   at t/ogf.t line 32.
#          got: undef
#     expected: '44100'

#   Failed test 'Song length ok'
#   at t/ogf.t line 33.
#          got: undef
#     expected: '1626'

#   Failed test 'Total samples ok'
#   at t/ogf.t line 34.
#          got: undef
#     expected: '71748'

#   Failed test 'VENDOR ok'
#   at t/ogf.t line 36.
#          got: undef
#     expected: 'reference libFLAC 1.3.4 20220220'

#   Failed test 'TITLE ok'
#   at t/ogf.t line 37.
#          got: undef
#     expected: 'Electronic'

#   Failed test 'ALBUM ok'
#   at t/ogf.t line 38.
#          got: undef
#     expected: 'Mutant Funk'
Error: Unable to read at least 10 bytes from file.

#   Failed test 'ALLPICTURES ok'
#   at t/ogf.t line 46.
#          got: ''
#     expected: 'ARRAY'

#   Failed test 'ALLPICTURES count ok'
#   at t/ogf.t line 47.
#          got: '0'
#     expected: '1'

#   Failed test 'Picture 0 ok'
#   at t/ogf.t line 51.
#          got: ''
#     expected: 'HASH'

#   Failed test 'Color index ok'
#   at t/ogf.t line 52.
#          got: undef
#     expected: '0'

#   Failed test 'Depth ok'
#   at t/ogf.t line 53.
#          got: undef
#     expected: '24'

#   Failed test 'Description ok'
#   at t/ogf.t line 54.
#          got: undef
#     expected: ''

#   Failed test 'Height ok'
#   at t/ogf.t line 55.
#          got: undef
#     expected: '300'

#   Failed test 'Image data ok'
#   at t/ogf.t line 56.
#          got: undef
#     expected: '37175'

#   Failed test 'JPEG data ok '
#   at t/ogf.t line 57.
#          got: ''
#     expected: 'ffd8ffe0'

#   Failed test 'MIME type ok'
#   at t/ogf.t line 58.
#          got: undef
#     expected: 'image/jpeg'

#   Failed test 'Picture type ok'
#   at t/ogf.t line 59.
#          got: undef
#     expected: '3'

#   Failed test 'Width ok'
#   at t/ogf.t line 60.
#          got: undef
#     expected: '301'
Error: Unable to read at least 10 bytes from file.

#   Failed test 'Audio offset ok'
#   at t/ogf.t line 69.
#          got: undef
#     expected: '106744'

#   Failed test 'Seek offset ok'
#   at t/ogf.t line 70.
#          got: undef
#     expected: '106744'

#   Failed test 'Seek header ok'
#   at t/ogf.t line 71.
#          got: undef
#     expected: '98411'
Error: Unable to read at least 10 bytes from file.

#   Failed test 'Audio offset ok'
#   at t/ogf.t line 80.
#          got: undef
#     expected: '106744'

#   Failed test 'Seek offset ok'
#   at t/ogf.t line 81.
#          got: undef
#     expected: '193419'

#   Failed test 'Seek header ok'
#   at t/ogf.t line 82.
#          got: undef
#     expected: '98411'
Error: Unable to read at least 10 bytes from file.

#   Failed test 'Bits per sample ok'
#   at t/ogf.t line 95.
#          got: undef
#     expected: '16'

#   Failed test 'Channels ok'
#   at t/ogf.t line 96.
#          got: undef
#     expected: '2'

#   Failed test 'Max blocksize ok'
#   at t/ogf.t line 97.
#          got: undef
#     expected: '4096'

#   Failed test 'Max framesize ok'
#   at t/ogf.t line 98.
#          got: undef
#     expected: '16394'

#   Failed test 'MD5 ok'
#   at t/ogf.t line 99.
#          got: undef
#     expected: '00000000000000000000000000000000'

#   Failed test 'Min blocksize ok'
#   at t/ogf.t line 100.
#          got: undef
#     expected: '4096'

#   Failed test 'Min framesize ok'
#   at t/ogf.t line 101.
#          got: undef
#     expected: '12572'

#   Failed test 'Samplerate ok'
#   at t/ogf.t line 102.
#          got: undef
#     expected: '44100'

#   Failed test 'Song length ok'
#   at t/ogf.t line 103.
#          got: undef
#     expected: '0'

#   Failed test 'Total samples ok'
#   at t/ogf.t line 104.
#          got: undef
#     expected: '0'

#   Failed test 'VENDOR ok'
#   at t/ogf.t line 106.
#          got: undef
#     expected: 'reference libFLAC 1.2.1 20070917'
# Looks like you failed 45 tests of 45.
t/ogf.t ............ Dubious, test returned 45 (wstat 11520, 0x2d00)
Failed 45/45 subtests
t/ogg.t ............ ok
...
Test Summary Report
-------------------
t/ogf.t          (Wstat: 11520 Tests: 45 Failed: 45)
  Failed tests:  1-45
  Non-zero exit status: 45
Files=20, Tests=1289, 16 wallclock secs ( 0.59 usr +  0.03 sys =  0.62 CPU)
Result: FAIL
Failed 1/20 test programs. 45/1289 subtests failed.
gmake: *** [Makefile:1030: test_dynamic] Error 255
```

With the changes required to get ogf.c to compile with VS2008, the tests all pass but one.
```
t\musepack.t ....... ok
t\ogf.t ............ 14/45 Error: Unable to read at least 28 bytes from file.
t\ogf.t ............ ok
t\ogg.t ............ ok
t\opus.t ........... ok
t\util.t ........... ok
t\wav.t ............ ok
t\wavpack.t ........ ok
All tests successful.
Files=20, Tests=1289, 10 wallclock secs ( 0.11 usr +  0.31 sys =  0.42 CPU)

```


@986ster would you kindly provide me with a couple of the ogf files you've been using for testing?

**Comment by 986ster** [comment]
> @986ster would you kindly provide me with a couple of the ogf files you've been using for testing?

Sure. There's a 16-44.1kHz and a 24-96 file here:
https://drive.google.com/drive/folders/14wWtw9FsuU2tVIy2gz-PjZfTgZBDXYLl?usp=drive_link

Can you let me know when you have them, so I can remove the files.

**Comment by ralph-irving** [comment]
> Can you let me know when you have them, so I can remove the files.
I've downloaded both of them.  Thank you.

**Comment by philippe44** [comment]
@ralph-irving I'm a bit confused with your statement about initial PR failing. It's because of arithmetic on void pointers? So the ogf.c is not compiled at all, no?

**Comment by ralph-irving** [comment]
As a sanity test, I am trying to confirm that the code changes in PR#5 work okay on 64bit windows, which so far, I've been unable to get working. The module build fine, but fails the test suite.

The gmake test output I posted, was built from strawberry perl 64bit windows, and is from strictly the source code changes provided here, none of my changes for VC2008 were applied.

**Comment by philippe44** [comment]
Understood - I could not either run the test suite of win64 build but I ran successfully the DLL in a live LMS environment under win64 (and did scanning and seeking of course)

**Comment by ralph-irving** [comment]
Thanks for confirming.
The DLL does NOT work for ogf files for me in my test environment, which is the one I setup to create the initial win64 LMS release.  I'll have to revisit this later on, but something isn't quite right.  The tests should pass and we really need to figure out why.  It will make it hard to automate building audio::scan if/when we get to that point.

**Comment by philippe44** [comment]
I'll take another look but the problem for me was that under strawberry x64 the whole test suite just does not run. None, any format, any test.

**Comment by philippe44** [comment]
There is one thing I can offer in ogg.c is to not even try to scan audio if the file is just a header. That makes the test pass without a warning and it still a valid decision for other cases but I don't think that was your issue. Now, I was able to make the test run under Win64 using gmake instead of nmake, my bad. That all works now.

My test environment is just strawberry 5.32 in portable mode, Win11 and Audio::Scan 1.10
```
perl Makefile.PL
gmake test
```

```
gmake test
"C:\Strawberry-5.32\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- Scan.bs blib\arch\auto\Audio\Scan\Scan.bs 644
"C:\Strawberry-5.32\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/01use.t .......... ok
t/02pod.t .......... skipped: set TEST_POD to enable this test
t/03podcoverage.t .. skipped: set TEST_POD to enable this test
t/04critic.t ....... ok
t/aac.t ............ ok
t/aiff.t ........... ok
t/asf.t ............ ok
t/dsdiff.t ......... ok
t/dsf.t ............ ok
t/flac.t ........... ok
t/mac.t ............ ok
t/mp3.t ............ ok
t/mp4.t ............ 1/120 Ignoring empty box of type mdat in: D:\Users\phili\Dropbox\Development\Audio-Scan\t\mp4\heaac.mp4
t/mp4.t ............ ok
t/musepack.t ....... ok
t/ogf.t ............ ok
t/ogg.t ............ ok
t/opus.t ........... ok
t/util.t ........... ok
t/wav.t ............ ok
t/wavpack.t ........ ok
All tests successful.
Files=20, Tests=1289,  3 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: PASS
```

**Comment by philippe44** [comment]
Let me know if there is something else I can do to help

**Comment by philippe44** [comment]
Do you think you could that with upcoming LMS 8.5? I think @michaelherger plans to release it soon.
Thanks

**Comment by ralph-irving** [comment]
I have been unable to get these changes to work on win64 in a similar environment to you nor on a debian 12 armhf system which is perl 5.36 or older x86_64 linux with perl 5.34.

I get this message in the logs on linux
```
Not a Vorbis file (bad vorbis header): /export/music0/PreProcessed/03-OGGFLAC-44.1-16.ogg
Not a Vorbis file (bad vorbis header): /export/music0/PreProcessed/03-OGGFLAC-96-24.ogg
Not a Vorbis file (bad vorbis header): /export/music0/PreProcessed/03-OGGFLAC-44.1-16.ogg
Not a Vorbis file (bad vorbis header): /export/music0/PreProcessed/03-OGGFLAC-96-24.ogg
```
I also built a debug version for win64 but that wasn't much help either.

I can release 1.10 anyway, but I can't say I expect it to work for everyone.
The fact that I can't get these changes to play local ogg/flac files on 3 different systems concerns me.
I've been support audio:scan for a long time and this is the first time that I've been unable to get new features to work.

**Comment by philippe44** [comment]
How have these files being built and also what is the environment where it fails? Is it LMS? I'm asking that because the right extension for OggFlac is ogf, not ogg, so yes, if you feed an OggFlac file to LMS with a .ogg extension, the parser will fail but as it would if you feed it an opus file with a .ogg extension instead of a .ops, I think.

**Comment by ralph-irving** [comment]
How stupid of me.  All 3 systems point to the same shared file system.
Changed the extension and bingo it works.
I've been doing this too long I think as I know that's the case.
I'll commit the PR and create the release.

**Comment by philippe44** [comment]
Never happened to me 😄 

BTw, on this OggFlac effort, I can't remember if I was clear, but the modified version of libflac works to have squeezelite being able to decode OggFlac with chained steams, but I also modified the flac standalone application so that if LMS needs to proxy such chained stream, it will work as well (needs an additional command line par later). Maybe I should coordinate with @mherger to see if we want to include that new flac binary in 8.5

**Pull request merged**
